### ISSUE TITLE
Is subreddits.json up to date?

### ISSUE THREAD

**Issue by Xalaxis** [gerenook/titletoimagebot#1]
Hi there, I'm /u/Xalaxis, moderator on /r/disneyvacation.  It seems your bot is being used on our sub.  That's good!  People like it.  But doesn't that mean that subreddits.json is missing "disneyvacation"?

Just being curious into exactly which subs the bot is looking at.  Congratulations on the bot!

**Comment by gerenook** [comment]
Hello! You're right, I haven't pushed the latest commit yet, give me a second.
Thanks for the kind words!
