### ISSUE TITLE
Font size

### ISSUE THREAD

**Issue by MakotoE** [gerenook/titletoimagebot#2]
Great bot! It's really funny when it's used on the right images. I just have a suggestion to increase the font size, because it's often kind of small compared to the images. Take a look at these two recent examples I picked at random: https://i.imgur.com/GhOjdmq.png https://i.imgur.com/oOXBUND.png I would guess maybe 1.5 to 2 times the current size might look better. It does seem like it appears smaller on taller images.

**Comment by ChildishGiant** [comment]
Maybe using OCR the font size in the source image could be matched. This'd solve the issue on the first example.

**Comment by MakotoE** [comment]
@ChildishGiant That seems overkill, and I feel like that would end up creating unintended results.

Edit: by unintended results, I mean that the bot wouldn't be able to tell if the title is supposed to connect to the text, or if it is completely separate.

**Comment by MakotoE** [comment]
I believe using a bold font may be better too. I edited the second example:
![ooxbund](https://user-images.githubusercontent.com/36318069/42600308-b072f6f6-8516-11e8-80e9-a94540f2e146.png)
and here is the GIMP file if you want to play around with it: http://www.mediafire.com/view/f5eo4qan6rumryo/oOXBUND.xcf/file . It uses Arial Bold. When I open images that TitleToImageBot made, I often see the picture first, before the title. I think that the first thing someone sees should be the title.

**Comment by gerenook** [comment]
I increased the font size by ~20%, let's see how it works out.

I still don't know what font to use, because I can't find one that support all emojis and unicode characters and works in Pillow.

**Comment by MakotoE** [comment]
Looks fantastic! 👌👌👌👌👌👌👌

I just did a quick Google search for emoji fonts and I found this, if you want to give it a try: https://github.com/MorbZ/OpenSansEmoji
